name: DevSecOps Pipeline


on:
    push:
        branches: [main]
    pull_request:

jobs:
    security:
        runs-on: ubuntu-latest

        steps: 
            
            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0

            - name: Gitleaks Secret Scanning
              uses: gitleaks/gitleaks-action@v2
              

            - name: Vulnerability Scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: '.'
                format: 'sarif' #Static Analytic Results Interchange Format
                output: 'trivy-results.sarif'

            - name: ZAP Scan
              uses: zaproxy/action-baseline@v0.12.0


            


